# Generated by Django 4.1.7 on 2023-11-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='about',
            field=models.CharField(default='about', max_length=1000),
        ),
    ]
