# Generated by Django 4.1.7 on 2023-11-25 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_newuser_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='data analyst', max_length=300)),
                ('job_description', models.CharField(default='abc', max_length=1000)),
                ('department', models.CharField(default='sales', max_length=300)),
                ('location', models.CharField(default='hubli', max_length=300)),
                ('word_mode', models.CharField(default='work from office', max_length=100)),
                ('no_of_vacancy', models.CharField(default='2', max_length=100)),
                ('mandatory_skills', models.CharField(default='HTML', max_length=500)),
                ('optional_skills', models.CharField(default='C', max_length=500)),
                ('experince', models.CharField(default='fresher', max_length=200)),
                ('salary', models.CharField(default='3LPA', max_length=400)),
                ('qualification', models.CharField(default='BCA', max_length=300)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=1)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
