# Generated by Django 4.1.7 on 2023-11-25 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_jobdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetails',
            old_name='experince',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='jobdetails',
            old_name='word_mode',
            new_name='work_mode',
        ),
    ]
