# Generated by Django 4.1.7 on 2023-11-26 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_applicationstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationStatus',
        ),
    ]
