# Generated by Django 4.1.7 on 2023-11-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_applicationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='email_password',
            field=models.CharField(default='password', max_length=400),
        ),
    ]
