# Generated by Django 4.1.7 on 2023-11-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_jobdetails_email_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='email_password',
        ),
        migrations.AddField(
            model_name='newuser',
            name='email_password',
            field=models.CharField(default='password', max_length=400),
        ),
    ]
