# Generated by Django 4.1.7 on 2023-11-28 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_remove_jobdetails_email_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('mode_of_interview', models.CharField(default='IN_office', max_length=500)),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.appliedjobs')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
