# Generated by Django 4.1.7 on 2023-12-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_agency_company_agencyjobdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency_company',
            name='c_email',
            field=models.EmailField(default='xyz@gmail.com', max_length=254),
        ),
    ]
