# Generated by Django 4.1.7 on 2023-12-03 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_agency_company_c_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyjobdetails',
            name='agency_id',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
