# Generated by Django 4.1.7 on 2023-12-04 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_agencyappliedjobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='rejected', max_length=500)),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.agencyappliedjobs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
