# Generated by Django 4.1.7 on 2023-12-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_agencyscheduleinterview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencyscheduleinterview',
            old_name='application_id',
            new_name='a_application_id',
        ),
    ]
