# Generated by Django 4.1.7 on 2023-12-06 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_rename_job_id_agencyappliedjobs_a_job_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencyappliedjobs',
            old_name='a_job_id',
            new_name='job_id',
        ),
        migrations.RemoveField(
            model_name='agencyscheduleinterview',
            name='a_application_id',
        ),
        migrations.AddField(
            model_name='agencyscheduleinterview',
            name='application_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.agencyappliedjobs'),
        ),
    ]
