# Generated by Django 4.1.7 on 2023-12-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_rename_a_job_id_agencyappliedjobs_job_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyjobdetails',
            name='job_type',
            field=models.CharField(default='Full time', max_length=100),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='job_type',
            field=models.CharField(default='Full time', max_length=100),
        ),
    ]
