# Generated by Django 4.1.7 on 2023-12-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_alter_agencyjobdetails_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencyscheduleinterview',
            old_name='agency_id',
            new_name='companyIdOrAgencyId',
        ),
        migrations.RenameField(
            model_name='scheduleinterview',
            old_name='company_id',
            new_name='companyIdOrAgencyId',
        ),
    ]
