# Generated by Django 4.1.7 on 2023-12-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_rename_agency_id_agencyscheduleinterview_companyidoragencyid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='about',
            field=models.CharField(default='Passionate professional dedicated to driving innovation and fostering growth through collaboration and strategic expertise.', max_length=1000),
        ),
    ]
