# Generated by Django 4.1.7 on 2023-12-23 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_userdetails_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyJobSaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField(default=django.utils.timezone.now)),
                ('companyIdOrAgencyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyId', to=settings.AUTH_USER_MODEL)),
                ('job_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.jobdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyJobSaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField(default=django.utils.timezone.now)),
                ('companyIdOrAgencyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencyId', to=settings.AUTH_USER_MODEL)),
                ('job_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.agencyjobdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
