# Generated by Django 4.1.7 on 2023-12-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_companyjobsaved_agencyjobsaved'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyappliedjobs',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.AddField(
            model_name='appliedjobs',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
    ]
