# Generated by Django 4.2.6 on 2024-01-01 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_companydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='founded_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
