# Generated by Django 4.2.6 on 2024-01-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_alter_companydetails_founded_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyjobdetails',
            name='country',
            field=models.CharField(default='India', max_length=300),
        ),
        migrations.AddField(
            model_name='agencyjobdetails',
            name='state',
            field=models.CharField(default='Karnataka', max_length=300),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='country',
            field=models.CharField(default='India', max_length=300),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='state',
            field=models.CharField(default='Karnataka', max_length=300),
        ),
    ]
