# Generated by Django 4.2.6 on 2024-01-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0031_remove_newuser_email_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
