# Generated by Django 4.2.6 on 2024-01-04 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_newuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='top company', max_length=600)),
                ('company_logo', models.ImageField(default='company logo', upload_to='uploaded_images/')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='question', max_length=3000)),
                ('answer', models.CharField(default='answer', max_length=5000)),
                ('designation', models.CharField(default='none', max_length=300)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.topcompanies')),
            ],
        ),
    ]
